### ISSUE TITLE
Use PREFIX in Turtle

### ISSUE THREAD

**Issue by rubensworks** [w3c/sparql-query#118]
As suggested by @afs in https://github.com/w3c/sparql-update/pull/31#discussion_r1311608934, we should replace the `@prefix` syntax in Turtle examples to `PREFIX`.

**Comment by afs** [comment]
I've added "discuss-f2f" for a group-wide view on use of `PREFIX` and `@prefix`.

**Comment by niklasl** [comment]
+1 for using the SPARQL syntax; to aid with e.g. copy-pasting. I'd prefer lower-case `prefix` in Turtle, since it is intended to be read by humans (and a `text/*` media-type, not an `application/*` one). SPARQL is more technical, designed to be more recognizable for SQL users.

**Comment by afs** [comment]
TriG is "application/trig".
Turtle as "text/turtle" was inherited by RDF 1.1 WG and could not be changed.

**Comment by niklasl** [comment]
Also use `BASE` over `@base`.

@afs True, so it seems I argued for using different forms for those, which would be very confusing. Consistency is paramount, we should use one form for the bulk of the specs, and also make it clear when we introduce the syntax that variations are allowed. And then say something like "in these specs, the PREFIX and BASE forms will be used for consistency".

**Comment by afs** [comment]
From TPAC 23:
"proposal: use PREFIX in specs over @prefix across all documents"

(@afs assumes that applies to BASE as well)
