### ISSUE TITLE
Definition of 'Group' operator insufficient

### ISSUE THREAD

**Issue by hartig** [w3c/sparql-query#131]
The [Group algebra operator](https://www.w3.org/TR/sparql-query/#defn_algGroup) is currently defined as follows (screenshot taken from the current WD).

![image](https://github.com/w3c/sparql-query/assets/584467/5c78956b-58c2-4423-9f0c-7ff954197bcb)

Notice that the formula in this definition contains the following sub-formula.

ListEval(exprlist, μ) = ListEval(exprlist, μ')

The ListEval function that is used in this formula returns a list of elements that may be RDF terms or errors. The issue now is that there is no definition of what exactly the `=` operator means in this case (at least, I cannot find something like it anywhere in the document). To make the definition of the Group operator unambiguous we should extend the definition to be explicit about the meaning of `=`.

Related to the issue, and as a possible solution, remember that I recently improved the definition of the Dedup helper function within the definition of the [Aggregation algebra operator](https://www.w3.org/TR/sparql-query/#defn_algAggregation). In that context, I added a definition to specify what it means for two such lists to be the same (from the perspective of deduplication). The relevant part of this definition looks as follows.

![image](https://github.com/w3c/sparql-query/assets/584467/e1271b44-402a-41f9-a24a-7f6668a0bf5a)

Notice that the first sub-bullet point in this definition is based on the semantics of [`SAMETERM`](https://www.w3.org/TR/sparql-query/#func-sameTerm). 

Now the question is whether we can simply adopt this definition also for the aforementioned `=` operator in the definition of [Group](https://www.w3.org/TR/sparql-query/#defn_algGroup)? In other words, is the intention of that `=` operator to also use the `SAMETERM` semantics when pairwise comparing the elements of the two lists?

**Comment by rubensworks** [comment]
I also think that the `SAMETERM` semantics is the intended one for the Group operator.
At least, that's how I have it implemented on my end.

**Comment by hartig** [comment]
I have checked in the implementation of Jena's query processor. This one also uses the `SAMETERM` semantics for grouping.

**Comment by hartig** [comment]
I just checked the grouping-related tests in the SPARQL test suite at https://github.com/w3c/rdf-tests/tree/main/sparql/sparql11/grouping  but none of these tests covers a case that is related to our question here.

As there seems to be consensus to use SAMETERM semantics for grouping, I will create a PR to make that explicit in the document, and I will prepare a corresponding test that can be added to the test suite (once the SPARQL 1.1 test suite has been carried over for SPARQL 1.2).

**Comment by hartig** [comment]
As promised above, I have created the PR with the changes that make the definition of the Group operator more explicit. See #132 

Now, I have also created a corresponding test to be integrated into the [SPARQL test suite](https://github.com/w3c/rdf-tests/tree/main/sparql). I have tried the test with Apache Jena, which passes the test successfully. While the [SPARQL test suite](https://github.com/w3c/rdf-tests/tree/main/sparql) still needs to be adapted to SPARQL 1.2, I am posting the corresponding files here.

A standalone manifest file, `manifest.ttl`, that be used to run the test (and that can be merged into https://github.com/w3c/rdf-tests/blob/main/sparql/sparql11/grouping/manifest.ttl) is:
```turtle
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix :       <http://www.w3.org/2009/sparql/docs/tests/data-sparql11/grouping/manifest#> .
@prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#> .
@prefix mf:     <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#> .
@prefix qt:     <http://www.w3.org/2001/sw/DataAccess/tests/test-query#> .
@prefix dawgt:  <http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#> .

<>  rdf:type mf:Manifest ;
    rdfs:label "Grouping" ;
    mf:entries
    ( 
    :group02
    ) .


:group02 rdf:type mf:QueryEvaluationTest ;
    mf:name "Group-2";
    rdfs:comment    "Grouping with literals" ;
    dawgt:approval dawgt:Proposed ;
    mf:action
         [ qt:query  <group02.rq> ;
           qt:data   <group-data-3.ttl> ] ;
    mf:result  <group02.srx>
    .
```

The file with the SPARQL query, `group02.rq`, is:
```sparql
PREFIX : <http://example/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

SELECT ?v (COUNT(*) AS ?cnt)
{
  ?s :p ?v .
}
GROUP BY ?v
```
The corresponding data file, `group-data-3.ttl`, is:
```turtle
@prefix : <http://example/> .
@prefix xsd:    <http://www.w3.org/2001/XMLSchema#>

:s1 :p "1"^^xsd:integer .
:s2 :p "1"^^xsd:integer .
:s3 :p "001"^^xsd:integer . 
:s4 :p "1"^^xsd:string .
```
And the SPARQL result file with the expected query result, `group02.srx`, is:
```xml
<?xml version="1.0"?>
<sparql xmlns="http://www.w3.org/2005/sparql-results#">
  <head>
    <variable name="v"/>
    <variable name="cnt"/>
  </head>
  <results>
    <result>
      <binding name="v">
        <literal datatype="http://www.w3.org/2001/XMLSchema#integer">1</literal>
      </binding>
      <binding name="cnt">
        <literal datatype="http://www.w3.org/2001/XMLSchema#integer">2</literal>
      </binding>
    </result>
    <result>
      <binding name="v">
        <literal datatype="http://www.w3.org/2001/XMLSchema#integer">001</literal>
      </binding>
      <binding name="cnt">
        <literal datatype="http://www.w3.org/2001/XMLSchema#integer">1</literal>
      </binding>
    </result>
    <result>
      <binding name="v">
        <literal datatype="http://www.w3.org/2001/XMLSchema#string">1</literal>
      </binding>
      <binding name="cnt">
        <literal datatype="http://www.w3.org/2001/XMLSchema#integer">1</literal>
      </binding>
    </result>
  </results>
</sparql>
```

**Comment by kasei** [comment]
New test looks good, but I think the manifest needs an `mf:requires` statement indicating that this test relies on no numeric canonicalization during loading. Some systems will fail this test simply because they canonicalize on import. (I thought we already had an IRI defined for such a `mf:requries` statement, but can't find anything in the existing manifest files.)

**Comment by afs** [comment]
I think the `=` in the definition is part of a function definition (e.,g., `f(x) = x+1`) so it is same term.

**Comment by hartig** [comment]
@afs 
> I think the `=` in the definition is part of a function definition (e.,g., `f(x) = x+1`) so it is same term.

No, the `=` that this is all about (which is the second `=` in the formula of the pre-PR #132 definition of Group) is not part of a function definition but it is a form of comparison operator within a condition part of the formula, and the meaning of this particular comparison operator was not clearly defined.
