### ISSUE TITLE
The SPARQL grammar allows expression syntax triple terms to have triple terms as subjects.

### ISSUE THREAD

**Issue by afs** [w3c/sparql-query#158]
Discovered because of https://github.com/w3c/rdf-tests/pull/144.
```
## expr-tripleterm-02.rq
PREFIX : <http://example.com/ns#>

SELECT * {
  ?s ?p ?o .
  BIND(<<( <<(?s ?p ?o)>> :q :z )>> AS ?t)
}
```
This should made invalid syntax.

**Comment by kasei** [comment]
I wonder if this is actually something that needs to change in the grammar as opposed to having some editorial text added. It feels similar to the grammar allowing literals in the subject position of triple patterns.

**Comment by afs** [comment]
(the argument can't pushed too hard - the purest view would be to allow literals as predicates!)

Personally, I don't have strong opinion as long as the syntax for triple-term-in-pattern and triple-term-in-expression are the same.
This, in Turtle, is an area of debate in the WG.

https://github.com/w3c/rdf-tests/issues/140 has them in the subject position.

Would you like to raise a general issue? and allow the current restricted/safe grammar to go into the editors' working draft?

Logistically, I think its better to get a consolidated editors working draft + issues than have long-running and potentially overlapping PRs.

**Comment by afs** [comment]
@kasei - Thanks for the reply.

#159 is cautious - it has the syntax restriction - but of course that could change and now has limited impact on the rest of the grammar.

The definition of SPARQL is simpler if it works with generalized subjects.

The CONSTRUCT query type already has text to the effect "only valid triples" (for literals in the subject position).

**Comment by kasei** [comment]
> The definition of SPARQL is simpler if it works with generalized subjects.

Agreed. Following this idea, it occurred to me that we might not want to prevent something like this:

```
<<( :s :p :o )>> ^rdf:reifies ?reifier
```
