### ISSUE TITLE
2 unused grammar productions

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/sparql-query#163]
If you search for "no references" in https://rawgit2.com/VladimirAlexiev/grammar-diagrams/master/sparql12-grammar.xhtml, you find two productions that are not used anywhere:
```
[69]  	ReifierData	  ::=  	'~' ReifierId?
[103]  	Integer    	  ::=  	INTEGER
```

**Comment by afs** [comment]
Done as part of #159.
