### ISSUE TITLE
RDF 1.1 Alignment - RDF Term and RDF Dataset

### ISSUE THREAD

**Issue by afs** [w3c/sparql-query#28]
`RDF Term` and `RDF dataset` were incorporated into RDF 1.1 (after SPARQL 1.1 was published).

We can switch to the definitions there.

`RDF dataset` added blank nodes for graph named (to accommodate JSON-LD).

**Comment by TallTed** [comment]
@hartig wrote in https://github.com/w3c/rdf-star-wg/issues/37#issuecomment-1476110780:
> Indeed, the definition of 'RDF dataset' in RDF 1.1 and in SPARQL 1.1 is slightly different. The difference is in terms of what can be a name of the named graphs that are contained in such a dataset. For the notion of [RDF dataset in RDF 1.1](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-dataset), the graph names can be IRIs or blank nodes, whereas for the notion of [RDF dataset in SPARQL 1.1](https://www.w3.org/TR/sparql11-query/#sparqlDataset), the graph names can only be IRIs. I guess that this difference is also something we want to get rid of.

The definition in RDF 1.1 is later, and should be preferred over that in SPARQL 1.1.
