### ISSUE TITLE
SHA-3

### ISSUE THREAD

**Issue by domel** [w3c/sparql-query#31]
I'm not sure if this isn't too far-fetched of a change but after SPARQL 1.1 came out SHA-3 was published. I wonder if appropriate functions analogous to sha256, sha512 could be added?

**Comment by afs** [comment]
Is the best way to add `SHA3_224()`, `SHA3_256()`, `SHA3_384()`, `SHA3_512()` ?

Or `SHA512("alg", text)` where "alg" is "sha3" or "sha2"

Or `SHA("alg", text)` where "alg" is "sha3-512" or "sha2-256?

Or `HASH("alg", text)` where "alg" is "sha3-512" or "sha2-256"

Do the current "SHA*" function get used in the real applications?

When first added, the availability of implementations was a concern. They all seem to be available in Apache Commons Digest and as Rust crates.

**Comment by rubensworks** [comment]
While I would definitely like this functionality to be added to the spec, I believe it doesn't fit into the current charter, so we probably shouldn't add it here.

**Comment by afs** [comment]
@domel - how about creating a SEP?

https://github.com/w3c/sparql-12/blob/main/SEP/README.md

**Comment by domel** [comment]
@afs - done https://github.com/w3c/sparql-12/pull/183
