### ISSUE TITLE
Idea: Datatype triple patterns

### ISSUE THREAD

**Issue by IS4Code** [w3c/sparql-query#56]
Hi! Sorry if this is not a proper place to submit this, however this is something I would find beneficial to be possible with SPARQL, and I would like to see it considered:

Presently, SPARQL triple syntax does not offer enough granularity when matching literals ‒ the object of a property can be specified in a triple pattern as (among others) a variable or a fixed literal, but it cannot be something in between. If you want to find triples based on the datatypes, you have to match all of them, and then filter:
```sparql
?s ?p ?o .
FILTER (DATATYPE(?o) = xsd:integer)
```
To optimize this query, SPARQL processors have to perform more complicated analysis, but all of this could be prevented with a more expressive triple pattern. I propose an extension of the node syntax like this:
```sparql
?s ?p ?o^^xsd:integer .
```
Such a query would only match triples with the `xsd:integer` datatype, and bind `?o` to the lexical value of the literal (as a simple literal/`xsd:string`).

Of course there are other options for the object:
```sparql
# any literal with this lexical value, regardless of datatype (?dt is bound to IRI)
?s ?p "10"^^?dt .

# any literal (?o is simple literal, ?dt is IRI)
?s ?p ?o^^?dt .
```

I think this would add more expressiveness to the language, and a possibility for better optimizations to triple store that can index by the datatype and evaluate such queries efficiently.

#### Language-tagged literals

These are literals as well, but I am unsure whether they should be matched by a pattern like `?o^^?dt`. However, if they are allowed, I think the natural solution (if not deemed too convoluted) might be to bind `?dt` to a literal with the `xsd:language` datatype, essentially treating something like `"hello world"@en` as "`"hello world"^^"en"^^xsd:language`", so `?o` would be `"hello world"` and `?dt` would be `"en"^^xsd:language`. After all, a language tag *is* the datatype of a language-tagged literal.

Other SPARQL functions, such as `STRDT`, could be modified to allow either `IRI` or `xsd:language` as the datatype.

**Comment by afs** [comment]
The SPARQL-dev community group might be a better place. See, for example, nearby: https://github.com/w3c/sparql-12/issues/34

> To optimize this query, SPARQL processors have to perform more complicated analysis, but all of this could be prevented with a more expressive triple pattern.

Could say more? Are there any system that currently make use of this as an optimization? 

Information can be indirect - a filter `(?X =10)` means `?X` is a literals and has certain XSD datatype choices. this includes derived types. Typically (if there is such thing) engines decompose syntax into independent operations and choose a good order for those operations.

**Comment by IS4Code** [comment]
Thank you! Yes, it might be better to post it there.

> Are there any system that currently make use of this as an optimization?

I am not aware of such systems. You are right however that even `FILTER(?o=10)` could be optimized away and turned into `?s ?p 10 .`, but it's still more complex than just stating that outright.

**Comment by afs** [comment]
Beware that that optimization is not valid in general. Triple patterns match by "same term", meaning same lexical form (string equality) and same datatype (same URI for the datatype). Filter function `sameTerm(?o, 10)`.

`?o = 10` is a value equality and is true for ?o being 10.0 (xsd:decimal), "010"^^xsd:integer (non-canonical lexical form), "+10"^^xsd:integer (non-canonical lexical form), "10"^^xsd:int (XSD derived datatype), 1e1 (xsd:double). The function is [op:numeric-equal](https://www.w3.org/TR/xpath-functions-3/#func-numeric-equal).
