### ISSUE TITLE
Clarify scoping of blank nodes in CONSTRUCT queries

### ISSUE THREAD

**Issue by rubensworks** [w3c/sparql-query#63]
As discussed in https://github.com/comunica/comunica/issues/1190, the working in https://www.w3.org/TR/sparql11-query/#templatesWithBNodes can be confusing, and could be interpreted incorrectly.
We should make it clear that blank node scoping only applies to blank nodes in the query template, but not to blank nodes in the dataset.

**Comment by afs** [comment]
@rubensworks - is this all resolved by PR#65 and we can close the issue?

**Comment by rubensworks** [comment]
Yes, indeed!
